version: "3"

services:
  gateway:
    build:
      context: .
      dockerfile: DockerfileGateway
    ports:
      - 81:81
    depends_on:
      - db
  transaction:
    build:
      context: .
      dockerfile: DockerfileTransaction
    ports:
      - 82:82
    depends_on:
      - db
      - rabbit_mq
  profile:
    build:
      context: .
      dockerfile: DockerfileProfile
    ports:
      - 83:83
    depends_on:
      - db
  product:
    build:
      context: .
      dockerfile: DockerfileProduct
    ports:
      - 84:84
    depends_on:
      - db
  identity:
    build:
      context: .
      dockerfile: DockerfileIdentity
    ports:
      - 85:85
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      COUNT: "123"
  db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  rabbit_mq:
    image: rabbitmq:3.7.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672